/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mempool_MemPool */

#ifndef _Included_com_example_mempool_MemPool
#define _Included_com_example_mempool_MemPool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mempool_MemPool
 * Method:    initPool
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_mempool_MemPool_initPool
  (JNIEnv *, jclass);

/*
 * Class:     com_example_mempool_MemPool
 * Method:    alloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_mempool_MemPool_alloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_mempool_MemPool
 * Method:    free
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_mempool_MemPool_free
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
