/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mempool_GCTest */

#ifndef _Included_com_example_mempool_GCTest
#define _Included_com_example_mempool_GCTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mempool_GCTest
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_example_mempool_GCTest_allocate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_mempool_GCTest
 * Method:    free
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_example_mempool_GCTest_free
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
